# Terminal Control MCP Server Configuration
# Modern TOML configuration with all default values

[web]
enabled = false
host = "0.0.0.0"
port = 8080
# external_host = ""  # Optional external hostname for URLs

[security]
level = "high"  # off, low, medium, high
max_calls_per_minute = 60
max_sessions = 50

[session]
default_shell = "bash"
timeout = 30

[logging]
level = "INFO"  # DEBUG, INFO, WARNING, ERROR

# Note: agent_name is handled dynamically per connection, not configured statically