server:
  name: "interactive-automation"
  version: "1.0.0"
  max_sessions: 50
  default_timeout: 3600
  log_level: "INFO"

security:
  enable_command_filtering: true
  enable_rate_limiting: true
  max_calls_per_minute: 60
  allowed_commands:
    - ssh
    - scp
    - mysql
    - psql
    - gdb
    - lldb
    - pdb
    - docker
    - git
    - python
    - node
    - echo
    - cat
    - ls
    - pwd
    - cd
    - which
    - whoami
  
  blocked_patterns:
    - "rm\\s+-rf\\s+/"
    - "dd\\s+if=.*of=/dev/"
    - "mkfs"
    - "format"
    - "shutdown"
    - "reboot"

automation:
  enable_predefined_patterns: true
  pattern_timeout: 30
  max_automation_steps: 100

debugging:
  enable_crash_analysis: true
  gdb_timeout: 300
  max_analysis_depth: "comprehensive"

logging:
  log_file: "/var/log/interactive-automation-mcp.log"
  log_rotation: true
  max_log_size: "10MB"
  backup_count: 5